services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hkn_portal
      POSTGRES_USER: hkn_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hkn_user -d hkn_portal"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    image: hknkappapsidev/hkn-portal:latest
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: myapp.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

      POSTGRES_DB: hkn_portal
      POSTGRES_USER: hkn_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    volumes:
      - .:/hkn-portal
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

volumes:
  pgdata: